### ISSUE TITLE
not working with newer python

### ISSUE THREAD

**Issue by Ishikudeska** [jnraber/VirtualDeobfuscator#4]
using python 3.11.2

PS C:\Users\m\Desktop> py C:\Users\mason\Desktop\fuck\VirtualDeobfuscator.py -c -d 1
Traceback (most recent call last):
  File "C:\Users\m\Desktop\fuck\VirtualDeobfuscator.py", line 26, in <module>
    import utils as u
  File "C:\Users\m\Desktop\fuck\utils.py", line 38
    gen_ids = lambda(x): "".join(map(chr, (ord('a')+(y%26) for y in range(x))))
                    ^^^
SyntaxError: Lambda expression parameters cannot be parenthesized

**Comment by Ishikudeska** [comment]
fixed utils as u myself but line 38 is just messing with me

**Comment by Ishikudeska** [comment]
was mad because utils was imported as "u"
fixed all instances of that
time for line 38 troublshooting

**Comment by Ishikudeska** [comment]
main problem currently is "Lambda expression parameters cannot be parenthesized"
I look through and find lambda expressions, but it still yells at me when I change them
